### ISSUE TITLE
Broke with 3.9.1 upgrade

### ISSUE THREAD

**Issue by kdpawson** [bludit-themes/docs-x#3]
Hi

This theme no longer works with my Bludit after upgrading to 3.9.1 - other themes work fine.
I get the main header bar and no content below that.

Running private Intranet with the following config:
LXC/LXD Container Ubuntu 18.04
nginx version: nginx/1.14.0 (Ubuntu)
PHP 7.2.17-0ubuntu0.18.04.1

Here is the nginx error log when browsing the main page:
2019/06/01 06:23:40 [error] 245#245: *70 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Site::googleplus() in /var/www/html/bludit/bl-themes/docs-x-2.0/php/navbar.php:53
Stack trace:
#0 /var/www/html/bludit/bl-themes/docs-x-2.0/index.php(13): include()
#1 /var/www/html/bludit/bl-kernel/boot/site.php(26): include('/var/www/html/b...')
#2 /var/www/html/bludit/index.php(41): require('/var/www/html/b...')
#3 {main}
  thrown in /var/www/html/bludit/bl-themes/docs-x-2.0/php/navbar.php on line 53" while reading upstream, client: 172.16.16.46, server: flathead.winnet.net, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "flathead.winnet.net"

Thanks
Keith

**Comment by dignajar** [comment]
I updated the theme, download the version 2.1.
https://themes.bludit.com/theme/docs-x

**Comment by kdpawson** [comment]
Thanks for the quick fix, all good again!
