### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by marcusyoung** [bludit-themes/docs-x#6]
@clickwork-git There seems to be  a problem with the layout in the latest version (v2.2)

The footer line and copyright notice are position on the far right and far left, rather than in line with the rest of the page contents.

![2020-08-21_17-26-34](https://user-images.githubusercontent.com/10391966/90913241-e2bf1680-e3d3-11ea-91c7-2253ae0c8349.jpg)

**Comment by marcusyoung** [comment]
The search plugin also doesn't work with the theme.

**Comment by clickwork-git** [comment]
1) The problem with the footer is fixed.
2) The search plugin cannot used with the theme. The [Bludit documentation](https://docs.bludit.com) uses [Algolia](https://www.algolia.com).

**Comment by marcusyoung** [comment]
Great, thanks for the fix.

**Comment by clickwork-git** [comment]
v3.0 works with the search plugin.
