### ISSUE TITLE
Page TOC

### ISSUE THREAD

**Issue by marcusyoung** [bludit-themes/docs-x#7]
@clickwork-git  In the Bludit documentation site there is a TOC for each page. Is this possible to achieve using the docs-x theme?

**Comment by clickwork-git** [comment]
You have to use the HTML tag _h2_ to create the TOC. If there are two or more h2 the TOC will be created.

Also if you use Markup you have to use _h2_ instead of _##_.

**Comment by marcusyoung** [comment]
Oh, right. I see. Thanks.

The h2 headings change the cursor to the link cursor on mouseover, even though they aren't links.

**Comment by clickwork-git** [comment]
Fixed.

**Comment by clickwork-git** [comment]
> You have to use the HTML tag _h2_ to create the TOC. If there are two or more h2 the TOC will be created.

Also you have to give the HTML tag _h2_ an ID ( _\<h2 id="..."\>_).
